# Singular-Value Decomposition

Dekomposisi Nilai-Singular, atau disingkat SVD, adalah metode dekomposisi matriks untuk mereduksi matriks menjadi bagian-bagian penyusunnya agar perhitungan matriks berikutnya menjadi lebih sederhana.

Untuk kasus kesederhanaan kita akan fokus pada SVD untuk matriks bernilai riil dan mengabaikan kasus untuk bilangan kompleks.

A = U . Sigma . V^T

Di mana A merupakan matriks mxn riil yang hendak didekomposisi, U merupakan matriks mxm, Sigma (sering dilambangkan dengan huruf Yunani kapital Sigma) merupakan matriks diagonal mxn, dan V^T merupakan transpos matriks nxn di mana T merupakan superskrip.

Nilai diagonal dalam matriks Sigma dikenal sebagai nilai singular dari matriks asli A. Kolom-kolom matriks U disebut vektor singular kiri dari A, dan kolom-kolom dari V disebut vektor singular kanan dari A.

SVD dihitung melalui metode numerik iteratif. Kami tidak akan membahas detail metode ini. Setiap matriks persegi panjang memiliki dekomposisi nilai singular, meskipun matriks yang dihasilkan mungkin berisi bilangan kompleks dan keterbatasan aritmatika floating point dapat menyebabkan beberapa matriks gagal terurai dengan rapi.

SVD digunakan secara luas baik dalam perhitungan operasi matriks lainnya, seperti invers matriks, tetapi juga sebagai metode reduksi data dalam pembelajaran mesin. SVD juga dapat digunakan dalam regresi linier kuadrat terkecil, kompresi gambar, dan penghilangan derau pada data.

# Hitung Dekomposisi Nilai Singular

SVD dapat dihitung dengan memanggil fungsi svd()

Fungsi ini mengambil matriks dan mengembalikan elemen U, Sigma, dan V^T. Matriks diagonal Sigma dikembalikan sebagai vektor nilai singular. Matriks V dikembalikan dalam bentuk transposisi, misalnya VT

Contoh berikut mendefinisikan matriks 3×2 dan menghitung dekomposisi nilai singular.

In [1]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("matrix awal : ",A)
# SVD
U, s, VT = svd(A)
print("U = :",U)
print("s = :",s)
print("VT = :",VT)

matrix awal :  [[1 2]
 [3 4]
 [5 6]]
U = : [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
s = : [9.52551809 0.51430058]
VT = : [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


Menjalankan contoh tersebut mula-mula akan mencetak matriks 3x2 yang telah ditentukan, kemudian matriks U 3x3, vektor Sigma 2 elemen, dan elemen matriks V^T 2x2 yang dihitung dari dekomposisi.

# Rekonstruksi Matriks dari SVD

Matriks asli dapat direkonstruksi dari elemen U, Sigma, dan V^T.

Elemen U, s, dan V yang dikembalikan dari svd() tidak dapat dikalikan secara langsung.

Vektor s harus diubah menjadi matriks diagonal menggunakan fungsi diag(). Secara default, fungsi ini akan membuat matriks persegi berukuran nxn, relatif terhadap matriks asli kita. Hal ini menyebabkan masalah karena ukuran matriks tidak sesuai dengan aturan perkalian matriks, di mana jumlah kolom dalam matriks harus sesuai dengan jumlah baris dalam matriks berikutnya.

Setelah membuat matriks diagonal Sigma persegi, ukuran matriks tersebut relatif terhadap matriks mxn asli yang sedang kita dekomposisi, sebagai berikut:

U (m x m) . Sigma (n x n) . V^T (n x n)

Di mana, pada kenyataannya, kita memerlukan:

U (m x m) . Sigma (m x n) . V^T (n x n)

Kita dapat memperolehnya dengan membuat matriks Sigma baru dengan semua nilai nol yang berukuran mxn (misalnya lebih banyak baris) dan mengisi bagian nxn pertama dari matriks tersebut dengan matriks diagonal persegi yang dihitung melalui diag().

In [2]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


A adalah sebuah matriks dengan ukuran 3×2, yaitu tiga baris dan dua kolom.
Matriks A berisi elemen-elemen sebagai berikut:
𝐴=[[1, 2], [3, 4], [5, 6]]

svd(A) melakukan dekomposisi nilai singular pada matriks A, menghasilkan tiga komponen:

- U: Matriks vektor singular kiri, berukuran 3×3.
- s: Vektor nilai singular, dengan panjang 2 (karena SVD menghasilkan nilai singular sebanyak dimensi minimum dari matriks asli, yaitu 2 dalam kasus ini).
- VT: Matriks transpos dari vektor singular kanan, berukuran 2×2.

Setelah SVD, kita memiliki hubungan:

                    A≈U⋅Σ⋅VT
                    
Di mana Σ adalah matriks diagonal yang berisi nilai-nilai singular.

- Sigma = zeros((A.shape[0], A.shape[1])) membuat matriks Sigma berukuran 3×2, yang diisi dengan nol.
- Ukuran ini mengikuti bentuk matriks A, dengan tujuan untuk merekonstruksi A dari dekomposisi nilai singular.

- diag(s) menghasilkan matriks diagonal dengan elemen-elemen dari vektor s pada diagonal utamanya.

- Sigma[:A.shape[1], :A.shape[1]] = diag(s) memasukkan nilai-nilai singular dari s pada bagian atas Sigma yang berukuran 2×2, meninggalkan baris ketiga dari Sigma tetap nol.

Hasil akhir Sigma setelah pengisian akan berbentuk:

Σ=[[s1,0],[0,s2],[0,0]]

Di mana 𝑠 dan 𝑠 adalah nilai-nilai singular dari s.

- Sigma.dot(VT) mengalikan Sigma dengan VT, menghasilkan matriks perantara berukuran 3×2.

- U.dot(...) kemudian mengalikan hasil tersebut dengan U, merekonstruksi matriks B yang seharusnya mendekati matriks asli A.

- Matriks B yang dihasilkan akan berukuran 3×2, sama dengan ukuran matriks asli A.

# implementasi data TFIDF dengan Matriks dari SVD

In [15]:
# Singular-value decomposition
import pandas as pd
from scipy.linalg import svd

# define a matrix
dfTFIDF = pd.read_csv('VSM dengan Pembobotan.csv')
dfTFIDF = dfTFIDF.drop("Unnamed: 0", axis='columns')
dfTFIDF
print("matrix awal : ",dfTFIDF)
# SVD
U, s, VT = svd(dfTFIDF)
print("U = :",U)
print("s = :",s)
print("VT = :",VT)

matrix awal :      abdominal  abdullah  abdurachman  abnormal  absen  abstrak  academy  \
0    0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
1    0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
2    0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
3    0.000000   0.04922          0.0       0.0    0.0      0.0      0.0   
4    0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
..        ...       ...          ...       ...    ...      ...      ...   
95   0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
96   0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
97   0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   
98   0.049152   0.00000          0.0       0.0    0.0      0.0      0.0   
99   0.000000   0.00000          0.0       0.0    0.0      0.0      0.0   

    acara  aceh  achilles  ...  yuli     yulia  zambo  zat  zedoaria  ziad  \
0     

In [4]:
import pandas as pd
from numpy import array, diag, dot, zeros
from scipy.linalg import svd

# Memuat matriks
dfTFIDF = pd.read_csv('VSM dengan Pembobotan.csv')
dfTFIDF = dfTFIDF.drop("Unnamed: 0", axis='columns')

In [5]:
# Melakukan Singular Value Decomposition
U, s, VT = svd(dfTFIDF)

In [32]:
U.shape

(100, 100)

In [33]:
s.shape

(100,)

In [34]:
VT.shape

(4600, 4600)

SVD(dfTFIDF) melakukan dekomposisi nilai singular terhadap dfTFIDF.
- Hasilnya:
    - U adalah matriks berukuran 100×100, yang berisi vektor-vektor singular kiri.
    - s adalah vektor dari nilai-nilai singular, dengan panjang 100 (karena SVD menghasilkan nilai singular sebanyak dimensi minimum dari matriks asli, yaitu 100).
    - VT adalah transpos dari vektor singular kanan, berukuran 100×4600.

In [6]:
# Membuat matriks Sigma dengan dimensi yang sesuai dengan U dan VT
Sigma = zeros((U.shape[1], VT.shape[0]))

- Sigma = zeros((U.shape[1], VT.shape[0])) membuat matriks Sigma dengan ukuran yang sama dengan U dan VT jika digabungkan, yaitu 100×4600.
- Sigma adalah matriks yang sebagian besar berisi nol, dan kita akan mengisi elemen-elemen diagonalnya dengan nilai singular dari s.

In [7]:
# Mengisi Sigma dengan nilai-nilai singular
Sigma[:len(s), :len(s)] = diag(s)

- diag(s) membuat matriks diagonal dengan elemen diagonal yang diambil dari vektor s.
- Sigma[:len(s), :len(s)] = diag(s) menempatkan nilai-nilai singular dari s di sepanjang diagonal utama Sigma, sehingga Sigma sekarang berukuran 100×4600 dan mengandung semua nilai singular pada posisinya.

In [8]:
# Merekonstruksi matriks
B = U.dot(Sigma.dot(VT))

- Sigma.dot(VT) mengalikan Sigma dengan VT, menghasilkan matriks perantara berukuran 100×4600.
- U.dot(...) kemudian mengalikan hasil tersebut dengan U, merekonstruksi matriks B yang sama ukurannya dengan matriks awal, yaitu 100×4600.
- B seharusnya mendekati matriks asli dfTFIDF karena proses SVD dan rekonstruksi matriks ini menghasilkan perkiraan dari matriks asli berdasarkan dekomposisi nilainya.

In [9]:
print(B)

[[ 6.27183219e-18 -3.62349946e-17 -2.31101304e-17 ... -2.07762978e-18
  -9.79552339e-17  1.21892790e-17]
 [ 6.44223249e-18 -1.72858663e-17 -2.29719713e-17 ...  6.78861471e-18
  -2.18827101e-17 -5.57792679e-18]
 [ 8.22044636e-18 -1.47968708e-18 -8.93312812e-18 ... -7.66575670e-18
  -2.32932172e-17  3.19215305e-18]
 ...
 [ 3.43813884e-19  2.30378533e-17  2.63609682e-17 ... -4.29508579e-17
  -1.17051389e-17  3.92833394e-17]
 [ 4.91520528e-02  3.07652001e-17 -4.71751764e-18 ...  8.16810318e-18
  -2.60809454e-17  4.30539435e-17]
 [-4.10341376e-19 -1.30166015e-17 -3.26549955e-17 ... -7.18925791e-18
  -2.14515113e-17 -7.10901637e-18]]


In [10]:
data_tfidf = pd.DataFrame(B)
data_tfidf

,0,1,2,3,4,5,6,7,8,9,...,4590,4591,4592,4593,4594,4595,4596,4597,4598,4599
0,6.271832e-18,-3.623499e-17,-2.311013e-17,4.781282e-18,6.541158e-18,2.115340e-18,6.304135e-18,7.416964e-18,2.061397e-17,-3.792391e-19,...,9.171960e-18,1.142808e-17,-1.879934e-18,6.571753e-18,3.942092e-18,1.233309e-17,2.399539e-18,-2.077630e-18,-9.795523e-17,1.218928e-17
1,6.442232e-18,-1.728587e-17,-2.297197e-17,1.058864e-17,1.976234e-17,-9.090524e-19,-2.499747e-19,-4.628347e-17,-1.274163e-16,-1.144182e-17,...,-2.569514e-17,6.659568e-18,-6.446968e-18,-6.918230e-18,-3.069293e-18,1.264645e-18,-1.372489e-18,6.788615e-18,-2.188271e-17,-5.577927e-18
2,8.220446e-18,-1.479687e-18,-8.933128e-18,-1.704657e-17,-8.220349e-18,3.422762e-18,6.375897e-18,-3.034355e-17,-8.014726e-18,-5.142372e-18,...,-6.416188e-18,-7.363446e-18,-7.881154e-18,1.515766e-17,-1.831434e-18,4.864388e-18,3.583436e-18,-7.665757e-18,-2.329322e-17,3.192153e-18
3,-1.632632e-17,4.921974e-02,2.732532e-17,1.426208e-17,-2.614698e-17,4.867503e-18,-3.051665e-18,-4.263888e-17,-1.218371e-16,1.285339e-17,...,-2.605730e-17,-1.029050e-19,-1.044711e-17,-9.906308e-19,2.800811e-17,-5.002910e-18,4.201347e-18,7.793935e-18,6.538289e-02,7.988794e-17
4,8.673594e-18,-2.482005e-17,-4.261072e-19,7.839407e-18,2.586649e-17,-5.464972e-18,2.970715e-17,-2.654283e-17,-4.253818e-17,-1.205427e-17,...,5.334172e-18,5.174695e-18,6.163081e-18,-1.561699e-17,1.728719e-17,3.040061e-17,-4.660611e-18,-6.855387e-20,-4.527973e-17,5.450255e-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.413378e-17,-3.698927e-17,6.810873e-18,-1.552399e-17,-1.713539e-17,-1.018993e-17,3.375623e-19,2.714341e-17,7.507100e-17,-1.007036e-17,...,2.348930e-17,4.474879e-02,8.286864e-18,-7.863636e-18,1.156472e-17,-1.717429e-17,-6.377664e-19,-5.993551e-18,-5.770746e-17,3.578846e-17
96,1.967691e-17,6.508652e-18,2.286421e-17,4.259166e-19,1.269441e-17,-1.285800e-17,-3.610964e-18,-4.845600e-17,-7.054174e-17,2.183387e-17,...,-1.418652e-17,6.535473e-18,-2.976463e-18,1.719385e-17,-1.368267e-17,2.004833e-18,3.461004e-18,1.052619e-17,-5.548667e-17,-4.389354e-17
97,3.438139e-19,2.303785e-17,2.636097e-17,-2.889484e-17,-2.751978e-17,9.342486e-18,3.572165e-18,-8.352505e-17,-1.185915e-16,8.919849e-18,...,4.851450e-18,9.610202e-18,-3.410089e-18,5.568054e-17,1.185344e-17,2.374624e-18,5.348665e-18,-4.295086e-17,-1.170514e-17,3.928334e-17
98,4.915205e-02,3.076520e-17,-4.717518e-18,2.982014e-17,-5.041803e-17,-1.552325e-17,-5.821887e-17,-5.881327e-17,-3.057598e-17,-2.634396e-17,...,-4.503768e-19,6.169738e-18,-3.257307e-18,-2.009778e-18,1.518651e-17,1.881147e-18,9.692244e-19,8.168103e-18,-2.608095e-17,4.305394e-17


In [31]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix

svd = TruncatedSVD(n_components=2600, n_iter=7, random_state=42)
databaru=svd.fit_transform(data_tfidf)
databaru.shape

(100, 100)